#!/bin/bash
PTH=./build/bdist.linux-x86_64/
#CNTER=d4-1.0
CNTER=d4-1.2
GRINGOPMS=--output smodels
#for older gringo versions
#GRINGOPMS=
$GRINGO_BIN_PATH $GRINGOPMS  |  $PTH/lp2lp2-1.23 | $PTH/lp2sat-1.24 | $PTH/pmc-1.0 -vivification -eliminateLit -litImplied -iterate=10 | $PTH/runsolver-3.4.0 -M 4096 -W 360 -w /dev/null $PTH/$CNTER -mc /dev/stdin
# 4096 is main memory limit in MB
# 360 is time limit in seconds
